// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ModernUwpDesigner
{
    internal sealed partial class Vsix
    {
        public const string Id = "ModernUwpDesigner.5fd8081f-8018-4306-b04a-3df569e8e18d";
        public const string Name = "Modern UWP Designer";
        public const string Description = @"Provides XAML Designer support for Modern UWP .NET 9+ projects";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Ahmed Walid";
        public const string Tags = "XAML, UWP, WinRT, Designer";
        public const bool IsPreview = true;
    }
}
