// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ModernUwpDesigner
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidModernUwpDesignerPackageString = "c87560ed-02e7-4c00-8dc6-b1ac79534ce4";
        public static Guid guidModernUwpDesignerPackage = new Guid(guidModernUwpDesignerPackageString);

        public const string guidModernUwpDesignerPackageCmdSetString = "8ebc6822-9501-41c9-b14b-b00316e47eb6";
        public static Guid guidModernUwpDesignerPackageCmdSet = new Guid(guidModernUwpDesignerPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ModernUwpDesignerGroup = 0x1020;
        public const int LaunchBlendCommandId = 0x0100;
        public const int DesignInBlendCommandId = 0x0101;
        public const int CreateBlendDesktopShortcutCommandId = 0x0102;
    }
}
